blueprint:
  name: Crewmeister automatisches Einstempeln
  description: |
    Stempelt automatisch in Crewmeister ein, sobald einer der definierten Auslöser greift.
    Unterstützt typische Szenarien wie das Verbinden mit einem bekannten WLAN, das Betreten
    einer Zone (Geofencing), das Scannen eines NFC-Tags oder zeitbasierte Trigger. Über ein
    optionales Zeitfenster lässt sich festlegen, wann frühestens bzw. spätestens automatisch
    eingestempelt wird. Zusätzlich können Notizen, Orte oder ein bestimmtes Crewmeister-Konto
    direkt aus dem Blueprint ausgewählt werden, um die Bedienung besonders komfortabel zu
    gestalten.
  domain: automation
  homeassistant: 2024.6.0
  source_url: https://raw.githubusercontent.com/crewmeister/hacs-crewmeister/main/blueprints/automation/crewmeister/clock_in.yaml

input:
  start_triggers:
    name: Auslöser
    description: |
      Füge alle Trigger hinzu, die das automatische Einstempeln starten sollen. Typische
      Beispiele sind das Verbinden mit einem bestimmten WLAN (State-Trigger auf den
      entsprechenden WLAN-Sensor), das Betreten einer Zone (Person- oder Device-Tracker),
      das Scannen eines NFC-Tags oder eine zeitgesteuerte Auslösung.
    selector:
      trigger: {}

  working_sensor:
    name: Crewmeister Arbeitsstatus (optional)
    description: |
      Wähle den Binärsensor "Eingestempelt" der Crewmeister-Integration aus, um zu verhindern,
      dass mehrfach eingestempelt wird, wenn der Status bereits aktiv ist.
    default: ""
    selector:
      entity:
        integration: crewmeister
        domain: binary_sensor

  block_helper:
    name: Sperr-Schalter (optional)
    description: |
      Ein (optional auszuwählender) Helper wie `input_boolean`, der bei "An" das automatische
      Einstempeln unterbindet. So lässt sich die Automatisierung z. B. bei Urlaub deaktivieren.
    default: ""
    selector:
      entity:
        domain:
          - input_boolean
          - switch

  use_time_window:
    name: Zeitfenster verwenden
    description: Aktiviere die Einschränkung auf ein bestimmtes tägliches Zeitfenster.
    default: false
    selector:
      boolean: {}

  earliest_time:
    name: Früheste automatische Einstempelzeit
    description: Wird nur berücksichtigt, wenn das Zeitfenster aktiviert ist.
    default: "07:00:00"
    selector:
      time: {}

  latest_time:
    name: Späteste automatische Einstempelzeit
    description: Wird nur berücksichtigt, wenn das Zeitfenster aktiviert ist. Bei Bedarf kann
      der Wert vor dem frühesten Zeitpunkt liegen, um einen Zeitraum über Mitternacht hinweg
      abzudecken.
    default: "11:00:00"
    selector:
      time: {}

  note:
    name: Notiz (optional)
    description: Wird an die Stempelung übermittelt, wenn ausgefüllt.
    default: ""
    selector:
      text:
        multiline: false

  location:
    name: Ort (optional)
    description: Optionaler Ortsname, der an Crewmeister übermittelt wird.
    default: ""
    selector:
      text:
        multiline: false

  time_account_id:
    name: Zeitkonto-ID (optional)
    description: Optionales Zeitkonto, das für die Stempelung genutzt werden soll.
    default: null
    selector:
      number:
        min: 1
        mode: box
        step: 1

  crewmeister_account:
    name: Crewmeister-Konto (optional)
    description: Nutze dieses Feld, wenn mehrere Crewmeister-Integrationen vorhanden sind und
      die Stempelung einem bestimmten Konto zugeordnet werden soll.
    default: ""
    selector:
      config_entry:
        integration: crewmeister

mode: single
max_exceeded: silent

variables:
  use_time_window: !input use_time_window
  earliest_time: !input earliest_time
  latest_time: !input latest_time
  working_sensor: !input working_sensor
  block_helper: !input block_helper
  note: !input note
  location: !input location
  time_account_id: !input time_account_id
  crewmeister_account: !input crewmeister_account

trigger: !input start_triggers

condition:
  - condition: template
    alias: Automatisierung nicht gesperrt
    value_template: >-
      {% if block_helper in ["", none] %}
        true
      {% else %}
        {{ states(block_helper) not in ["on", "unavailable", "unknown"] }}
      {% endif %}
  - condition: template
    alias: Noch nicht eingestempelt
    value_template: >-
      {% if working_sensor in ["", none] %}
        true
      {% else %}
        {{ states(working_sensor) != "on" }}
      {% endif %}
  - condition: template
    alias: Innerhalb des optionalen Zeitfensters
    value_template: >-
      {% if use_time_window %}
        {% set current_time = now().time() %}
        {% set earliest = strptime(earliest_time, "%H:%M:%S").time() %}
        {% set latest = strptime(latest_time, "%H:%M:%S").time() %}
        {% if earliest <= latest %}
          {{ earliest <= current_time <= latest }}
        {% else %}
          {{ current_time >= earliest or current_time <= latest }}
        {% endif %}
      {% else %}
        true
      {% endif %}

action:
  - variables:
      sanitized_note: "{{ (note | string).strip() }}"
      sanitized_location: "{{ (location | string).strip() }}"
      sanitized_account: >-
        {% if crewmeister_account is mapping %}
          {{ crewmeister_account.get("id", "") | string | trim }}
        {% else %}
          {{ (crewmeister_account | string).strip() }}
        {% endif %}
      sanitized_time_account: >-
        {% if time_account_id is number %}
          {{ time_account_id }}
        {% elif time_account_id is string and time_account_id | length > 0 %}
          {{ (time_account_id | int(0)) }}
        {% else %}
          {{ none }}
        {% endif %}
  - service: crewmeister.create_stamp
    data:
      stamp_type: START_WORK
      {% if sanitized_note %}
      note: "{{ sanitized_note }}"
      {% endif %}
      {% if sanitized_location %}
      location: "{{ sanitized_location }}"
      {% endif %}
      {% if sanitized_time_account is not none %}
      time_account_id: {{ sanitized_time_account }}
      {% endif %}
      {% if sanitized_account %}
      config_entry_id: "{{ sanitized_account }}"
      {% endif %}
