blueprint:
  name: Crewmeister automatisches Ausstempeln
  description: |
    Stempelt automatisch in Crewmeister aus, sobald einer der definierten Auslöser greift.
    Unterstützt typische Auslöser wie das Verlassen eines WLANs, das Verlassen einer Zone,
    das Scannen eines NFC-Tags beim Gehen oder feste Zeiten. Über ein optionales Zeitfenster
    kannst du festlegen, in welchem Zeitraum spätestens ausgestempelt werden soll. Damit sich
    das Blueprint gut in unterschiedliche Setups einfügt, lassen sich der Crewmeister-Account,
    eine Notiz, ein Ort sowie optionale Sperren komfortabel auswählen.
  domain: automation
  source_url: https://raw.githubusercontent.com/crewmeister/hacs-crewmeister/main/blueprints/automation/crewmeister/clock_out.yaml

input:
  stop_triggers:
    name: Auslöser
    description: |
      Füge alle Trigger hinzu, die das automatische Ausstempeln auslösen sollen. Beispiele
      sind das Trennen von einem WLAN, das Verlassen einer Zone, ein NFC-Tag an der Haustür
      oder eine bestimmte Uhrzeit.
    selector:
      trigger: {}

  working_sensor:
    name: Crewmeister Arbeitsstatus (optional)
    description: |
      Wähle den Binärsensor "Eingestempelt" der Crewmeister-Integration aus, um sicherzustellen,
      dass nur ausgestempelt wird, wenn tatsächlich Arbeitszeit läuft.
    default: ""
    selector:
      entity:
        integration: crewmeister
        domain: binary_sensor

  block_helper:
    name: Sperr-Schalter (optional)
    description: |
      Ein Helper wie `input_boolean` oder ein Schalter, der bei "An" das automatische
      Ausstempeln verhindert (z. B. für Überstunden oder Außentermine).
    default: ""
    selector:
      entity:
        domain:
          - input_boolean
          - switch

  use_time_window:
    name: Zeitfenster verwenden
    description: Aktiviere die Einschränkung auf ein tägliches Zeitfenster für das Ausstempeln.
    default: false
    selector:
      boolean: {}

  earliest_time:
    name: Früheste automatische Ausstempelzeit
    description: Wird nur berücksichtigt, wenn das Zeitfenster aktiviert ist.
    default: "14:00:00"
    selector:
      time: {}

  latest_time:
    name: Späteste automatische Ausstempelzeit
    description: Wird nur berücksichtigt, wenn das Zeitfenster aktiviert ist. Liegt der Wert vor
      der frühesten Zeit, gilt das Fenster über Mitternacht hinweg.
    default: "21:00:00"
    selector:
      time: {}

  note:
    name: Notiz (optional)
    description: Wird an die Stempelung übermittelt, wenn ausgefüllt.
    default: ""
    selector:
      text:
        multiline: false

  location:
    name: Ort (optional)
    description: Optionaler Ortsname, der an Crewmeister übermittelt wird.
    default: ""
    selector:
      text:
        multiline: false

  time_account_id:
    name: Zeitkonto-ID (optional)
    description: Optionales Zeitkonto, das für die Stempelung genutzt werden soll.
    default: null
    selector:
      number:
        min: 1
        mode: box
        step: 1

  crewmeister_account:
    name: Crewmeister-Konto (optional)
    description: Nutze dieses Feld, wenn mehrere Crewmeister-Integrationen vorhanden sind und
      die Stempelung einem bestimmten Konto zugeordnet werden soll.
    default: ""
    selector:
      config_entry:
        integration: crewmeister

mode: single
max_exceeded: silent

variables:
  use_time_window: !input use_time_window
  earliest_time: !input earliest_time
  latest_time: !input latest_time
  working_sensor: !input working_sensor
  block_helper: !input block_helper
  note: !input note
  location: !input location
  time_account_id: !input time_account_id
  crewmeister_account: !input crewmeister_account

trigger: !input stop_triggers

condition:
  - condition: template
    value_template: >-
      {% if block_helper in ["", none] %}
        true
      {% else %}
        {{ states(block_helper) not in ["on", "unavailable", "unknown"] }}
      {% endif %}
  - condition: template
    value_template: >-
      {% if working_sensor in ["", none] %}
        true
      {% else %}
        {{ states(working_sensor) == "on" }}
      {% endif %}
  - condition: template
    value_template: >-
      {% if use_time_window %}
        {% set now_time = now().time() %}
        {% set earliest = strptime(earliest_time, "%H:%M:%S").time() %}
        {% set latest = strptime(latest_time, "%H:%M:%S").time() %}
        {% if earliest <= latest %}
          {{ earliest <= now_time <= latest }}
        {% else %}
          {{ now_time >= earliest or now_time <= latest }}
        {% endif %}
      {% else %}
        true
      {% endif %}

action:
  - service: crewmeister.create_stamp
    data:
      {%- set note_value = note | trim %}
      {%- set location_value = location | trim %}
      {%- set time_account_value = none %}
      {%- if time_account_id is number %}
        {%- set time_account_value = time_account_id %}
      {%- elif time_account_id is string and time_account_id | length > 0 %}
        {%- set time_account_value = time_account_id | int %}
      {%- endif %}
      {%- set config_entry_value = '' %}
      {%- if crewmeister_account is mapping %}
        {%- set config_entry_value = crewmeister_account.get("id", "") | trim %}
      {%- else %}
        {%- set config_entry_value = (crewmeister_account | string) | trim %}
      {%- endif %}
      stamp_type: CLOCK_OUT
      {%- if note_value %}
      note: "{{ note_value }}"
      {%- endif %}
      {%- if location_value %}
      location: "{{ location_value }}"
      {%- endif %}
      {%- if time_account_value is not none %}
      time_account_id: {{ time_account_value }}
      {%- endif %}
      {%- if config_entry_value %}
      config_entry_id: "{{ config_entry_value }}"
      {%- endif %}
